### PR TITLE
Move snyk to devDependencies

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by ericblade** [comment]
Hi @edg2s !  Thank you for the pull request.  I believe that having snyk installed in deps instead of devDeps is as a result of using snyk protect.  Some information: https://support.snyk.io/hc/en-us/articles/360000911277-Why-has-Snyk-been-added-as-a-dependency-in-my-project-

However, this does at least bring up the question "do we need that".  My gut feeling, is that we might -- particularly with the number of packages that quagga still relies upon that are somewhat outdated (although I think I've got most everything that relates to production finally updated, I think there might be a few small ones..).

I'm going to keep this open for a little bit, and try to remember to look into it next time I am spending dev time on this project.  IF you have any supporting information as to why you think I shouldn't be using snyk protect, I'd be happy to hear that, also!

Thank you!

**Comment by edg2s** [comment]
Ok, I just assumed that as it wasn't used in the code anywhere that it should be a devdep.

**Comment by ericblade** [comment]
i think the gist of the answer, ultimately, is that snyk is (potentially? maybe not actually?) doing some patches after install of the lib, so it needs to be in deps so that it's available with NODE_ENV set to production... still, worth a little bit of looking into as to if it's actually doing anything.

**Comment by ericblade** [comment]
I have done some investigation of this, and have decided, mostly for the reasons above, that I am not going to make this move at this time.  Snyk will remain as a regular dependency for now, to offer the most protection against unmaintained modules or modules that are extremely difficult to upgrade, that are still in use from becoming security issues.

**Pull request closed without merging**
