### PR TITLE
Edit Code 32 and added new images for testing

### PR DESCRIPTION
**Pull request by stefanocali**

### CODE REVIEW

**Comment by stefanocali** [comment]
I tried using the compiled file to scan code 32 and they work.  But if the code 32 is close to the i2of5 code as in image number 6 (code 32 above and i2of5 code below), quagga finds it difficult to read it, but in the end he reads it.

**Comment by ericblade** [comment]
The tests running here are showing that the 9 new images are all skipping due to failure?  I know we do have a bunch of existing test failures in other readers, which highlight that the other readers are not working perfectly, but this is causing me to wonder if this reader is not working particularly well yet?

image

**Comment by stefanocali** [comment]
Hi Eric, I don't think it's a code 32 problem, otherwise experimenting with the compiled code wouldn't work.  I think it's more a problem read at code 39 (in tests I used only code 32 as a decoder, but it seems that it also detects the i2of5 code, I don't know if it is for the graphic form of the bar code) or only a problem during the  significantly of the code, which being close to other codes, takes longer to find it.

**Comment by ericblade** [comment]
hmm.  when i get some time, i'll try plugging them into a live reader, and see what happens

**Comment by stefanocali** [comment]
Hi Eric, are there any news? did you try it with a reader?

**Comment by ericblade** [comment]
i hadn't, sorry, my scant code time has been spread across two other projects as well, and since this one is working pretty well, i'm spending more time on the other two right now..  i did just assign it to myself so hopefully i'll remember to check it out shortly, but i'm not sure when that might be.   In the meantime, you're welcome to try to figure out what's going wrong, perhaps it needs different configuration settings, or something.

Do these images work when you use them?   If so, what are your quagga settings?

**Comment by stefanocali** [comment]
> 
> 
> i hadn't, sorry, my scant code time has been spread across two other projects as well, and since this one is working pretty well, i'm spending more time on the other two right now.. i did just assign it to myself so hopefully i'll remember to check it out shortly, but i'm not sure when that might be. In the meantime, you're welcome to try to figure out what's going wrong, perhaps it needs different configuration settings, or something.
> 
> Do these images work when you use them? If so, what are your quagga settings?

Quagga.init({
        inputStream: {
            name: "Live",
            type: "LiveStream",
            target: document.querySelector('#quagga-container'),
            constraints: {
                width: {min: 640},
                height: {min: 480},
                aspectRatio: {min: 1, max: 100},
                facingMode: "environment"
            },
        },
        locator: {
            patchSize: "large",
            halfSample: true
        },
        numOfWorkers: 4,
        decoder: {
            readers: [
                "code_32_reader"
            ]
        },

    }, function (err) {
        if (err) {
            return
        }

        Quagga.start();

        // Set flag to is running
        _scannerIsRunning = true;
    });

    Quagga.onProcessed(function (result) {
        var drawingCtx = Quagga.canvas.ctx.overlay,
        drawingCanvas = Quagga.canvas.dom.overlay;

        if (result) {
            if (result.boxes) {
                drawingCtx.clearRect(0, 0, parseInt(drawingCanvas.getAttribute("width")), parseInt(drawingCanvas.getAttribute("height")));
                result.boxes.filter(function (box) {
                    return box !== result.box;
                }).forEach(function (box) {
                    Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, { color: "green", lineWidth: 2 });
                });
            }

            if (result.box) {
                Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 }, drawingCtx, { color: "#00F", lineWidth: 2 });
            }

            if (result.codeResult && result.codeResult.code) {
                Quagga.ImageDebug.drawPath(result.line, { x: 'x', y: 'y' }, drawingCtx, { color: 'red', lineWidth: 3 });
            }
        }
    });

**Comment by stefanocali** [comment]
So I updated the file. Now it works live without any problems. I don't know why but using npm test doesn't work.

**Comment by ericblade** [comment]
Looks like a pretty big improvement there in how well it's working -- picks up half of the images provided now!

image

**Comment by ericblade** [comment]
@stefanocali I'm going to go ahead and merge this since it is an improvement in the results.  Your contributions are greatly appreciated!

**Pull request merged**
