### PR TITLE
removed injected clearfix br

### LINKED ISSUE #140: Added br causes flickering
There is a piece of code
```
function quagga_initCanvas() {
    // ... snip ...
      var clearFix = document.createElement('br');
      clearFix.setAttribute('clear', 'all');

      if ($viewport) {
        $viewport.appendChild(clearFix);
      }
    }
```

which makes the final HTML page jump after rendering the video element. Is there any technical reason for having this? Fromy my perspective it would be better to document any floating issue, instead of injecting this "rather broken fix" into the document.

Do you see any possibility of either reomving this completely or making it configurable?

### PR DESCRIPTION
**Pull request by kevinpapst**
Fixes #140 

Don't know if there is more to do than just removing the lines?!?
Tested the build and still works as before.

### CODE REVIEW

**Comment by ericblade** [comment]
So, it solves the problem you're having with it forcing a reflow?  I think that's probably good.  You're welcome to add yourself to the "contributors" section in package.json, push another commit with that, and .. it looks like the failure on Node 13 with macOS is due to something broken on the builder machine on github's side... so, i see no reason why not to accept this.  Thank you!

**Comment by kevinpapst** [comment]
Thanks for the offer! But this contribution is not worth a mention. I'll try to remember with the next one 😁 

Most of these building issues clear themselves with a rebuild. I tried to find a button to restart the job (like its available on Travis) but couldn't find it. 

So yes, my issue is gone now. I played around with the drawingBuffer as well, but as it is mentioned a couple of times throughout the codebase (seemingly only for debugging issues) I kept it for now.

**Comment by ericblade** [comment]
I'd check it out myself, but I'm not exactly sure how to even test for the layout issue, and it seems pretty corner case.  I doubt anyone's using float for anything anywhere anyway, if they are, they probably aren't tracking the latest of anything :-D

So I'll put that into the next release, and see if anyone complains :-D

**Comment by kevinpapst** [comment]
I can't think of any good reason to rely on that br clear fix. If anyone complains, they should fix it on their end ^^

**Pull request merged**
