### PR TITLE
WIP: Typescript

### PR DESCRIPTION
**Pull request by ericblade**

### CODE REVIEW

**Comment by ericblade** [comment]
Tests completely bomb out if attempting to use awesome-typescript-loader instead of babel-loader for them.  I don't have the slightest idea why right at this moment.  I'd like to be able to remove babel, if it's not necessary.

**Comment by ericblade** [comment]
... well, that's going to have to get fixed before we can proceed with any conversion to .ts .. since tests can't convert the ts to js, they can't run. :|

**Comment by jogibear9988** [comment]
I think you could use tsnode to run the tests directly via typescript.

**Comment by ericblade** [comment]
Tests written in Typescript are running just fine (the current test framework uses the PhantomJS browser to run tests in browser, rather than in node .. i'm not sure if there's *also* some node testing going on here, but I don't think there is)

I'm having an issue right now, where once I've converted the mediaDevices and CameraAccess modules to typescript, the CameraAccess tests all start failing.. trying to figure out if i've somehow changed the code in some fashion, or if there's some sort of failure on sinon's behalf related to using it with typescript

**Comment by ericblade** [comment]
This is exactly why I want to make sure that we do this in small commits -- I just spent quite some time tracking down exactly what changed in a single commit, and comparing it to the code that existed prior,  and was eventually able to figure out a way to nail down the problem.

If anyone else wants to contribute to this changeset, I'd welcome the help. :-D

**Comment by ericblade** [comment]
hmm. adding polyfills gives us a pretty sizeable increase in bundle size, which is not something that i particularly want to have happen.. but i also want to be able to use modern code.  

i think i'm going to yank the updates to array_helper that require polyfills for the PhantomJS version we're using, and move some "modernizing code" tasks to a point "after we significantly upgrade what runs our tests" .. because it's pretty inexcusable to have the test runner be as old as it is right now..

**Comment by ericblade** [comment]
fwiw, i'm hitting some pretty complex things as I dig further into it here, the pieces that are done seem to be working great, but i'm running into some pretty wild things in the remaining pieces ... on the bright side, though, i've got a pretty good idea of how all the pieces of the software all fit together now.. :-D

**Comment by ericblade** [comment]
@jogibear9988 if you or anyone else here happens to have any insight into what the functional differences are in this commit... https://github.com/ericblade/quagga2/commit/434919ae5c8698f73f5ef7b5c7a8e13d6bdb628b

... it's failing all tests, and i don't see how it should behave any different from the original source.  but it does. :(
no runtime errors, just image decoder isn't returning anything useful.. and i'm not quite sure how to debug inside that particular area.

**Comment by ericblade** [comment]
OK, *so*, this is not yet completed, however, I'm ready to pull this into master because I want to work on some other issues, and I want to base them on the typescript stuff because I think that's going to make it a hell of a lot easier to do certain refactorings, but I don't want to delay those fixes/features until completion of this task.

**Pull request merged**
