### PR TITLE
Expose READERS type instead of generic string

### PR DESCRIPTION
**Pull request by oidualc**

### CODE REVIEW

**Comment by ericblade** [comment]
Looks like a good change. I do need to understand if it breaks anything wrt using a reader that is external to the quagga source, though.

**Comment by oidualc** [comment]
Thank you! I just added myself to the list of contributors

**Comment by ericblade** [comment]
Hmm. OK, so after pulling this change in, I can no longer build a project that is dependent on quagga, because the import { READERS } line fails, as it's trying to point to source, rather than the built lib... 

Looking at it, I'm pretty sure that's why there's the whole "declare module Readers" section in the .d.ts, as I ran into that same problem when I tried to export Readers to begin with.

So, I think the correct solution appears to be to remove the import { READERS } line, and make the last line ```export type QuaggaJSCodeReader = keyof typeof Readers;``` .  That seems to work for the QR reader test suite.

Could you make that change, see if it still fits your use case, and if so, commit it?

Thanks!

**Comment by oidualc** [comment]
> So, I think the correct solution appears to be to remove the import { READERS } line, and make the last line `export type QuaggaJSCodeReader = keyof typeof Readers;` . That seems to work for the QR reader test suite.

But this would produce a different result than expected, we would like to have:
`type QuaggaJSCodeReader = "code_128_reader" | "ean_reader" | "ean_5_reader" | "ean_2_reader" | "ean_8_reader" | "code_39_reader" | "code_39_vin_reader" | "codabar_reader" | "upc_reader" | "upc_e_reader" | "i2of5_reader" | "2of5_reader" | "code_93_reader" | "code_32_reader"`

and instead this way we get:
`type QuaggaJSCodeReader = "BarcodeReader" | "TwoOfFiveReader" | "NewCodabarReader" | "Code128Reader" | "Code39Reader" | "Code32Reader" | "Code39VINReader" | "Code93Reader" | "EANReader" | "EAN2Reader" | ...`

If READERS cannot be exported maybe the solution would be to just hardcode the values, the only caveat is that in the future, if the READERS object keys are modified, the corresponding type in d.ts will have to be updated manually.
I just add a commit with this edit.

**Comment by ericblade** [comment]
ahh you are right about that.  I sort of missed the point of the change, I guess.  :)  
I'll go with this, if/when we ever have any future decoders, I'd prefer to ship them as external packages anyway, that have quagga as peerDeps, there's little reason to include all of the decoder/reader code in the main repo, and i hope to make the next major version have all separate readers, once i figure out a good process to configure test setups for them.

**Comment by ericblade** [comment]
Thanks for the submission!

**Pull request merged**
