### PR TITLE
Use per-method files when importing lodash

### PR DESCRIPTION
**Pull request by aihowes**
This decreases file size:

**Before**
Non-min: 3.8mb
Min: 285kb

**After**
Non-min 2.6mb
Min: 231kb

Testing using the dist files will be needed as I don't have a project setup on this computer for it.

Here's lodash's documentation on this:
https://lodash.com/per-method-packages

### CODE REVIEW

**Comment by ericblade** [comment]
Thank you!

THAT is beautiful!  I had poked at trying to remove lodash entirely for exactly the bundle size reason some time ago, but I didn't want to risk the side effects of replacing the merge function with something inferior, and having it come back to bite me in scenarios that aren't covered by automated testing.

With the test upgrades over the last several months, I'm much more confident that auto testing will catch if changes like this break things.  

If you'd like to, please add yourself to the contributors array in package.json !

**Comment by aihowes** [comment]
@ericblade Cheers, I'd be super grateful, if you could add the tag `hacktoberfest-accepted` to this PR once merged.

**Comment by ericblade** [comment]
Ah, sure, I just had to lookup what that was about.  Looks like I'll have to add it to the repository topics as well.  Thank you!

**Comment by ericblade** [comment]
image
image

**Comment by aihowes** [comment]
Good stuff! Another benefit is that webpack's default chunk size that it complained at was 250kb so now that we're below that user's should hopefully not get any messages about size. 👍

**Pull request merged**
